### ISSUE TITLE
To-do list.

### ISSUE THREAD

**Issue by AtomicFeasT** [AtomicFeasT/index-news#1]
## Major Changes
- [x] Change `gallery-section` images and description texts to new ones.
- [x] Create pages to every content in all sections.

### Small Changes 
- [x] Together with the existing `hover` in all contents, `ctg-title (<-- Name should change too)` should have an animation that goes from bottom to top showing a different background color.
- [x] All titles should have the new hr divider like gallery-hr does.
- [x] Change some classes names for better readibility.
